-- Sparkery dispatch finance immutable audit log
-- Run in Supabase SQL Editor.

create table if not exists public.dispatch_finance_audit_logs (
  id bigint generated by default as identity primary key,
  job_id text not null references public.dispatch_jobs(id) on delete cascade,
  action text not null check (
    action in (
      'finance_adjustment_applied',
      'finance_confirmed',
      'payment_received_marked',
      'payment_received_unmarked'
    )
  ),
  trace_id text not null,
  actor_user_id text null,
  actor_role text null,
  session_id text null,
  before_payload jsonb not null,
  after_payload jsonb not null,
  metadata jsonb null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_dispatch_finance_audit_job_created
  on public.dispatch_finance_audit_logs (job_id, created_at desc);

create index if not exists idx_dispatch_finance_audit_trace
  on public.dispatch_finance_audit_logs (trace_id);

create index if not exists idx_dispatch_finance_audit_action_created
  on public.dispatch_finance_audit_logs (action, created_at desc);

alter table public.dispatch_finance_audit_logs enable row level security;

drop policy if exists dispatch_finance_audit_select
  on public.dispatch_finance_audit_logs;
drop policy if exists dispatch_finance_audit_insert
  on public.dispatch_finance_audit_logs;
drop policy if exists dispatch_finance_audit_update
  on public.dispatch_finance_audit_logs;
drop policy if exists dispatch_finance_audit_delete
  on public.dispatch_finance_audit_logs;

create policy dispatch_finance_audit_select
on public.dispatch_finance_audit_logs
for select
to anon, authenticated
using (true);

create policy dispatch_finance_audit_insert
on public.dispatch_finance_audit_logs
for insert
to anon, authenticated
with check (true);

-- Immutable by policy: updates/deletes are blocked.
create policy dispatch_finance_audit_update
on public.dispatch_finance_audit_logs
for update
to anon, authenticated
using (false)
with check (false);

create policy dispatch_finance_audit_delete
on public.dispatch_finance_audit_logs
for delete
to anon, authenticated
using (false);
