-- Sparkery API support tables: idempotency + audit logs
-- Run in Supabase SQL Editor

create table if not exists public.sparkery_api_idempotency (
  endpoint text not null,
  idempotency_key text not null,
  request_hash text not null,
  status_code integer not null,
  response_payload jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (endpoint, idempotency_key)
);

create index if not exists idx_sparkery_api_idempotency_created_at
  on public.sparkery_api_idempotency (created_at desc);

create table if not exists public.sparkery_api_audit_logs (
  id bigint generated by default as identity primary key,
  request_id text not null,
  endpoint text not null,
  method text not null,
  status_code integer not null,
  duration_ms integer not null,
  idempotency_key text null,
  user_agent text null,
  caller_ip text null,
  error_message text null,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_sparkery_api_audit_logs_request_id
  on public.sparkery_api_audit_logs (request_id);

create index if not exists idx_sparkery_api_audit_logs_created_at
  on public.sparkery_api_audit_logs (created_at desc);

create index if not exists idx_sparkery_api_audit_logs_endpoint_created
  on public.sparkery_api_audit_logs (endpoint, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sparkery_api_idempotency_updated_at
  on public.sparkery_api_idempotency;

create trigger trg_sparkery_api_idempotency_updated_at
before update on public.sparkery_api_idempotency
for each row
execute function public.set_updated_at();
